export { ArchLensOrchestrator, createArchLensOrchestrator } from './orchestrator/index.js';
export type { ArchLensOrchestratorOptions } from './orchestrator/index.js';
export type { ScanOptions, InitOptions, InitResult, LoadedConfig } from './types.js';
export { loadArchLensConfig } from './config/load-config.js';
export { scaffoldConfig } from './config/scaffold-config.js';
export { scanWorkspaceFiles } from './fs/file-scanner.js';
export type { DependencyGraph, ImportReference } from './parser/ts-dependency-graph.js';
export { buildDependencyGraph, createDefaultResolver } from './parser/ts-dependency-graph.js';
export { reportViolations } from './reporter/console-reporter.js';
export type { ArchLensConfig } from './types.js';
